# Not sure why using download.docker.com repo and docker-ce doesn't work on swarm nodes and works on cd
# even through it's the same version of ubuntu
- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ debian_version }} main
    update_cache: yes
    state: present
  tags: [docker]

- name: Debian Docker is present
  apt:
    name: docker-engine
    state: latest
    force: yes
  tags: [docker]

- name: Debian python-pip is present
  apt:
    name: python-pip
    state: present
    force: yes
  tags: [docker]

- name: Debian docker-py is present
  pip:
    name: docker
    state: present
  tags: [docker]

- name: Debian files are present
  template:
    src: "{{ docker_cfg }}"
    dest: "{{ docker_cfg_dest }}"
  register: copy_result
  tags: [docker]

# - name: Debian Daemon is reloaded
  # command: echo 'hello'
  # when: copy_result|changed and is_systemd is defined
  # tags: [docker]

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result
  tags: [docker]

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  # when: copy_result|changed or user_result|changed
  tags: [docker]
